### PR TITLE
Provision CM magic methods based on async CM ones

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
Hey !

This PR implements auto-provisioning of `__enter__` and `__exit__` methods to provide an OOTB "sync" version of an object acting as an asynchronous context manager.

Note : any resource bound to an event loop and allocated in `__aenter__` **cannot** be released in `__aexit__` due to this library internals. Thus only "simple" asynchronous CMs **should** be wrapped this way 🙂

Thanks, bye 👋

### CODE REVIEW

**Comment by MrNaif2018** [comment]
Hi! Thank you very much for your PR! Please re-base (or allow edits from maintainers) to get the CI running (:

I have some questions though:

> Note : any resource bound to an event loop and allocated in `__aenter__` **cannot** be released in `__aexit__` due to this library internals. Thus only "simple" asynchronous CMs **should** be wrapped this way 🙂

What do you mean by this? Do you have any example? If it can't be released it might be a bug in the library.

Also I think the tests added don't test anything, we should check whether the session was closed via context manager's `__aexit__`
Thanks!

**Comment by HorlogeSkynet** [comment]
> What do you mean by this? Do you have any example? If it can't be released it might be a bug in the library.

For example, if you allocate a resource bound to an event loop (like an `asyncio.Server`) and try to _do_ something with it from another event loop (what actually happens when running in a separate thread : a new event loop is created for **each** synchronous call), it crashes.

```python
import asyncio
import threading

import universalasync


async def handle_echo(reader, writer):
    data = await reader.read(100)
    message = data.decode()
    addr = writer.get_extra_info('peername')
    print(f"Received {message!r} from {addr!r}")
    print(f"Send: {message!r}")
    writer.write(data)
    await writer.drain()
    print("Close the connection")
    writer.close()


@universalasync.async_to_sync_wraps
async def start_server():
    server = await asyncio.start_server(handle_echo, '127.0.0.1', 8888)
    addrs = ', '.join(str(sock.getsockname()) for sock in server.sockets)
    print(f'Serving on {addrs}')
    return server


@universalasync.async_to_sync_wraps
async def serve_forever(server):
    try:
        await server.serve_forever()
    except KeyboardInterrupt:
        server.close()
        await server.wait_closed()


def target():
    # A first event loop is created here :
    server = start_server()

    # A second different event loop is created here :
    serve_forever(server)


if __name__ == "__main__":
    # start and serve the server from another thread
    threading.Thread(target=target).start()
```

If I run `python3 -V && python3 main.py`, I get :

```
Serving on ('127.0.0.1', 8888)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/main.py", line 42, in target
    serve_forever(server)
  File "/path/to/universalasync/universalasync/wrapper.py", line 66, in async_to_sync_wrap
    return run_sync_ctx(coroutine, loop)
  File "/path/to/universalasync/universalasync/wrapper.py", line 32, in run_sync_ctx
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/path/to/main.py", line 35, in serve_forever
    await server.serve_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 366, in serve_forever
    await self._serving_forever_fut
RuntimeError: Task <Task pending name='Task-5' coro=<serve_forever() running at /path/to/main.py:35> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184]> got Future <Future pending> attached to a different loop
```

This very behavior _may_ also happen if you use `universalasync` to wrap an asynchronous context manager (what this PR implement !) : resources that are created in `__aenter__` might be attached to a different loop than the one running `__aexit__`.

**Comment by MrNaif2018** [comment]
Okay, I think I managed to fix your example: it should now work on master (7f92a89a9325407f7731a2901e56d29ff7c3ce73)
Not sure about the cleanup though, I removed it (it was like `asyncio.run`). I think it shouldn't do that because asyncio.run is for one-off operations while universalasync wrappers will be called constantly, without that your code won't work

**Comment by MrNaif2018** [comment]
Thank you very much for your PR! I will do follow up fixes in master

**Pull request merged**
